apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql-config
  namespace: wordpress
data:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"
  MYSQL_PASSWORD: "wordpresspassword"
  WORDPRESS_DB_HOST: "mysql"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_PASSWORD: "wordpresspassword"