apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
    skip_name_resolve
    bind-address=0.0.0.0    
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
    skip_name_resolve
    bind-address=0.0.0.0    